README.md
Let Composer figure out the version to install.
=> Let Composer figure out the version

composer.json
This commit adds an information that this replaces "sebastianfeldmann/captainhook"
=> Add replacement information in composer.json

src/Console/Application/Hook.php, src/Console/Command/Hook.php, src/Console/Command/Hook/PrepareCommitMsg.php
This adds functionality to allow not only a setup but also a teardown for the hooks
Time: 1h30m
=> WIP: Add first draft to extend hooks more flexibly

src/Console/Application/Hook.php, src/Hooks.php
This moves the definition of which HookClass shall be executed for which hook to the hook definition. With this change in place implementing a new Hook only requires one change in one existing file (Hooks) and the new HookClass extending Hook.
Time: 10m
=> Move Hook-Config into one single place

src/Console/Command/Hook.php
=> Fix: Grammar

src/Hook/Template/Local/Shell.php, tests/CaptainHook/Hook/Template/Local/ShellTest.php
This is an implementation for feature request https://github.com/CaptainHookPhp/captainhook/issues/87.
=> Allow hooks to prompt users for input

src/Console/Command/Hook.php, src/Hook/Message/Action/Book.php, src/Hook/PHP/Action/Linting.php, src/Runner/Action/Cli.php, src/Runner/Action/PHP.php, src/Runner/Hook.php
See #90: This adjusts the console output to better connect action logging + action errors. For CLI commands, it is now clearer which output came from which command.
=> Improve console output

favorites.html, index.html
Improve the documentation with a curated list of hooks.
=> Captains favorite hooks

src/Hook/Directory/Action/NotEmpty.php, src/Hook/File/Action/NotEmpty.php
With these hooks, the end user must define the a pathSrc (path source) and fileName (the name of a file that should be checked) in their respected actions.
=> Add empty file/folder hooks

src/Hook/File/Action/Check.php, src/Hook/File/Action/IsNotEmpty.php, tests/CaptainHook/Hook/File/Action/IsNotEmptyTest.php
Hook to check if a list files or directories is not empty.
You can use this to make sure you add README files.
=> Add not empty hook

src/Console/IOUtil.php, src/Hook/Message/Rule/LimitBodyLineLength.php, src/Hook/Message/Rule/LimitSubjectLength.php, src/Runner/Hook.php, tests/CaptainHook/Hook/Message/Action/RulesTest.php
=> Changed strlen to mb_strlen for line length rule

extend.html
Add a reference to the Infection plugin for CaptainHook.
=> Add Infection plugin reference

configure.html
Related PR: https://github.com/captainhookphp/captainhook/pull/119
=> Add basic documentation for php-path config option

configure.html, extend.html, index.html
This documentation supports the feature implemented in https://github.com/captainhookphp/captainhook/pull/125
You may see the documentation changes live here: https://ramsey.github.io/captainhook/
=> Add plugin documentation

configure.html
Fixed invalid json in docs example.
=> Fix typo in docs example

src/Console/Command/Install.php, src/Runner/Installer.php, tests/unit/Console/Command/InstallTest.php, tests/unit/Runner/InstallerTest.php
Linked issue - https://github.com/captainhookphp/captainhook/issues/203
=> Allow specifying multiple hooks

src/Config/Options.php, src/Console/Command/Uninstall.php, src/Hook/PHP/Action/TestCoverage.php, src/Runner/Files.php, src/Runner/Hook/PrepareCommitMsg.php, src/Runner/Installer.php, src/Runner/Uninstaller.php, tests/unit/Console/Command/UninstallTest.php, tests/unit/Mockery.php, tests/unit/Runner/Hook/PrepareCommitMsgTest.php, tests/unit/Runner/UninstallerTest.php
This will add a `captainhook uninstall` command that removes all hook scripts from your local `.git/hooks` directory.
=> Add uninstall command to the Cap'n

.docker/php8.2/Dockerfile, .docker/php8.3/Dockerfile, .github/workflows/integration.yml, docker-compose.yml
Add php 8.3 build
Add php 8.3 container config
=> Add PHP 8.3 build (experimental)

conditions.html
Actions here should be rewritten to conditions.
=> Update conditions.html - actions -> conditions

src/Config/Run.php, src/Hook/Template.php, src/Hook/Template/Builder.php, src/Hook/Template/Local/Shell.php, src/Hook/Template/Local/WSL.php, tests/unit/Hook/Template/Local/WSLTest.php
Hi, thanks for this project, this is a first draft regarding issue https://github.com/captainhookphp/captainhook/issues/156 which adds native WSL support. Basically it adds a new WSL run mode which only adds `wsl.exe` to the Shell command, which allows to run the command inside WSL.
=> WSL support

actions.html
This is related to PR: https://github.com/captainhookphp/captainhook/pull/266
Adjust documentation for new option `pattern`.
=> adjust documentation for new pattern option
