src/Hook/Message/Rule/Blacklist.php

For the body blacklist check, the subject blacklist is used - while the body blacklist is never used because of this bug.
I stumbled on this problem when I tried to commit with the usage of "created" in the message body, which lead to an incorrect "Execution failed: Subject should be written in imperative mood, Invalid use of 'created'" error.

Bug: Subject blacklist (for commit) used for body

---

src/Exception/ActionFailed.php
src/Hook/Message/Action/Beams.php

There's nothing more frustrating than writing a beautiful commit
message, then have having one stray too long line, or extra full stop
cause you to loose it all when the commit message linter triggers.
This change will allow the user to copy their commit message from the
terminal on failure, saving a whole bunch of frustration.

Print the commit message on BEAMS rules failure

---

composer.json
src/Console/Command/Hook/CommitMsg.php

For commit message hooks this will set the comment character based on
what the user has had set in their git config settings. This means that
if a user wants to be able, for example put a pull request ID (#123 for
example) at the start of their commit message, they can.

Set comment character based on users config

---

composer.json
src/Hook/Message/Action/Regex.php
tests/CaptainHook/Hook/Message/Action/RegexTest.php

Hi!
While using the RegEx action i missed the possibility to add better messages than just "Commit message did not match regex: #FoBar#" in the options.
The options "success" and "error" are purely optional and by using the "%s" operator in both of them, you can place the used regex anywhere you want.
Cheers!
Ben

Add messages to regex action

---

src/Hook/ActionFactory.php
src/Runner/Action/PHP.php

This adds the possibiliity to use an ActionFactory in the configuration instead of an Action directly.
The Options from the configuration are passed to the ActionFactory::getAction-Method to enable creation of customized classes. these classes need to implement the Action-Interface.
That way the creation of the custom-class is separated from the actual execution of the Action.

Add possibility to use ActionFactory

---

extend.html

I stumbled upon some minor logic and parse errors.
I don't know if they are on purpose, like:
```
in_array(date('D'), ['Mon, 'SAT'])
```
which will only hit on monday.
But anyway, I thought updating it to actually working code might be fine.
If not, I will revert them.

Update logic and "parse errors" on extend.html

---

captainhook-run
src/Console/Command/Install.php
src/Hook/Template/Builder.php
src/Hook/Template/Docker.php
src/Storage/Util.php
tests/CaptainHook/Hook/Template/DockerTest.php
tests/CaptainHook/Storage/UtilTest.php
tests/files/storage/captainhook-run

With latest PR #32 docker support was added. Sadly I forgot to cross check the complete implementation. This PR solves a problem with the correct execution path for the binary inside the docker container.

Fix: Docker binary path

---

composer.json

This PR
💁‍♂ We don't know yet whether this package will be compatible with PHP 9000.

Fix: Limit range of PHP versions

---

actions.html
composer.html
configure.html
extend.html
hooks.html
index.html
install.html

In the footer there were references to `gp-pages` instead of `gh-pages`.

[docs] Fix typo in footer

---

src/Config.php
src/Config/Action.php
src/Config/Condition.php
src/Config/Factory.php
src/Config/Hook.php
src/Config/Options.php
src/Config/Util.php
tests/CaptainHook/Config/FactoryTest.php
tests/CaptainHook/Config/HookTest.php
tests/files/config/invalid-with-nested-includes.json
tests/files/config/valid-include.json
tests/files/config/valid-nested-include.json
tests/files/config/valid-with-includes.json
tests/files/config/valid-with-invalid-includes.json
tests/files/config/valid-with-nested-includes.json

Hi @heiglandreas 
Could you have a look at this, and let me know what you think?
This adds the possibility to include `CaptainHook` configurations in `CaptainHook` configuration files.
Basically it would look like this
```javascript
{
"config": {
"includes": [
"vendor/my-company/hook-package/valid-include.json"
]
},
...
"pre-commit": {
"enabled": true,
"actions": [
{
"action": "phpunit --configuration=build/phpunit-hook.xml",
"options": []
}
]
},
...
}
```
If the included configuration would look like this
```javascript
{
"pre-commit": {
"enabled": true,
"actions": [
{
"action": "phpcs --standard=psr2 src",
"options": []
}
]
}
}
```
and you run `CaptainHook` with the first configuration both `pre-commit` actions would be executed.
This way you could create  a "company base packages" that …

Add config inclusion feature

---

src/Hook/Message/Rule/Blacklist.php
src/Hook/Message/Rule/UseImperativeMood.php
src/Hook/Message/RuleBook/RuleSet.php
tests/CaptainHook/Hook/Message/Rule/UseImperativeMoodTest.php

This allows the use of blacklisted words within the subject and only fails when they are found at the beginning of the subject. This only applies to using the beams-rule

Allow black listed words within subject

---

src/Config/Factory.php
tests/CaptainHook/Config/FactoryTest.php
tests/files/config/empty-with-includes.json
tests/files/config/valid-with-disabled-action.json

Consider this a rough draft to get some feedback on the idea, not a finished and polished implementation.
Right now, one can add extra actions through included configurations. If an included configuration has `"enabled": true` for some hook, that does not mean that hook is automatically enabled in the merged configuration. That means that when you use an included config, you still need to know what hooks that config defines and enable them. This PR also merges the `enabled`-flag from included configurations, so the latter is not necessary anymore. If either the main configuration or an included configuration has `"enabled": true`, that hook is enabled. 
I can image that it is slightly 'spooky' to have an included configuration enable a hook like this, therefore I'm first posting a rough …

[WIP] Allow included configurations to enable hooks

---

src/Console/Command/Install.php
src/Hook/Template/Builder.php
tests/CaptainHook/Hook/Template/BuilderTest.php

Because run-mode can be set in configuration, we need to check config too.
I updated Template\Builder so run-mode is passed via parameter.
Run-mode could be resolved again from input and config in builder without
the additional parameter but i felt like that would violate DRY.

Pass run-mode into Template\Builder from Command\Install

---

src/Console/Command/Install.php
src/Hook/Template/Builder.php
tests/CaptainHook/Hook/Template/BuilderTest.php

This commit fixes that the setup reads the docker-setup configuration
from the captainhook.json config file.
Currently the docker config can only be setup using the commandline
arguments on the `captainhook install` command. But for existing or new
setups where the configuration file is distributed that is not the
expected behaviour. The problem was that the Builder currently only
checks for the command-line options but ignores the configuration
option. The new behaviour also checks the config options and uses them
when no commandline arguments are passed. Therefore installations using
the captainhook composer plugin now will be able to install the docker
based setup from the commited config-file

Fix docker-setup with configuration file

---

tests/CaptainHook/Console/Command/AddTest.php
tests/CaptainHook/Console/Command/ConfigurationTest.php
tests/CaptainHook/Console/Command/DisableTest.php
tests/CaptainHook/Console/Command/EnableTest.php
tests/CaptainHook/Console/Command/Hook/CommitMsgTest.php
tests/CaptainHook/Console/Command/Hook/PostCheckoutTest.php
tests/CaptainHook/Console/Command/Hook/PostCommitTest.php
tests/CaptainHook/Console/Command/Hook/PostMergeTest.php
tests/CaptainHook/Console/Command/Hook/PreCommitTest.php
tests/CaptainHook/Console/Command/Hook/PrePushTest.php
tests/CaptainHook/Console/Command/Hook/PrepareCommitMsgTest.php
tests/CaptainHook/Console/Command/InstallTest.php

Hello, 
in symfony/console 4.4 .gitattributes file was added https://github.com/symfony/console/commit/c35a2fc5bd760385b234aee5d231aeb90d7f3741
and DummyOutput is now not shipped in composer, so i replaced DummyOutput with NullOutput for tests to pass.
#SymfonyHackday

Replace DummyOutput with NullOutput

---

src/Hook/File/Action/IsEmpty.php
tests/CaptainHook/Hook/File/Action/IsEmptyTest.php

Adds an action that checks whether the configured (static) files are empty, e.g. an application's error log file.

Add file is empty action

---

src/Config.php
src/Runner/Hook.php
tests/CaptainHook/Config/FactoryTest.php
tests/CaptainHook/ConfigTest.php
tests/files/config/valid-with-all-settings.json

This PR adds the `exec-all-actions` boolean setting. When enabled, all actions are executed (even if some of them fail). If any of these actions has failed, the hook finally finishes with a non-zero exit code.
Furthermore, I adjusted the console output to better connect action logging + action errors. For CLI commands, it is now clearer which output came from which command.

Add fail-at-first-error config setting

---

src/Hook/File/Action/DoesNotContainRegex.php
src/Hook/File/Action/NotContainsRegex.php
tests/CaptainHook/Hook/File/Action/DoesNotContainRegexTest.php
tests/files/storage/regextest1.txt
tests/files/storage/regextest2.txt

Adds an action that checks whether all staged files (may be filtered by file type) don't match the configured regex, e.g. to avoid some unwanted PHP functions.

Add file DoesNotContainRegex action

---

src/Config.php
src/Hook/Template/Builder.php
src/Hook/Template/Local.php
src/Hook/Template/Local/Shell.php
tests/CaptainHook/Hook/Template/Local/PHPTest.php
tests/CaptainHook/Hook/Template/Local/ShellTest.php

Fixes #117 
With this, we are adding new `php-path` config option which is used (if provided) when writing git hook, so it looks something like this:
```
/usr/bin/php7.4 vendor/captainhook/captainhook/bin/captainhook $INTERACTIVE --configuration=captainhook.json --bootstrap=vendor/autoload.php hook:pre-commit "$@" <&0
``` 
Docs PR: https://github.com/captainhookphp/captainhook/pull/120

Fixes #117 Feature/define php version

---

src/Hook/Condition/FileChanged/All.php
src/Hook/File/Action/Exists.php
src/Hook/File/Action/MaxSize.php

Fix some grammar issues in docblocks and exception messages.
Are Exception messages considered as public API or are those safe to change?

Fix grammar issues

---

tests/CaptainHook/Console/IO/ComposerIOTest.php

- According to the official [PHPUnit doc](https://phpunit.readthedocs.io/en/9.5/fixtures.html), it should be `protected function setUp(): void` and `protected function tearDown(): void`.

Improve PHPUnit fixtures

---

favorites.html

Some examples had invalid JSON syntax. With this change the syntax is valid now.

Fixed JSON Syntax

---

src/Config/Factory.php
src/Config/Util.php

This PR fixes the merging logic for includes from `captainhook.config.json`
fixes #144

add merging logic for includes from `captainhook.config.json`

---

composer.json

Changes `composer.json` to allow version `^6.0` of Symfony components. The tests all pass!

Allow use of Symfony v6 components

---

src/Runner/Condition.php

Currently it's not possible to use conditions that don't require args (have empty constructor) in logic conditions without explicitly defining `"args": []` in config file, which is superfluous.
PS. I have edited this file via Github web UI, hence "Unverified" commit.

Support condition without required args in logic conditions

---

install.html

On current MacOS, with up2date oh my zsh it is required NOT to run the composer run in a virtual shell, since the git doesnt output the content of the virtual shell used by docker behind the scenes

Avoids running docker-compose run command in a TTY

---

composer.json
src/Runner/Hook.php
src/Runner/Hook/CommitMsg.php
tests/unit/Runner/Hook/CommitMsgTest.php

Because you can skip commit messages for fixup commits completely it does not make sense to validate them.

Skip message validation for fixup commits

---

.docker/php7.3/Dockerfile
.docker/php7.4/Dockerfile
.docker/php8.1/Dockerfile
.docker/php8.2/Dockerfile
docker-compose.yml
phive.xml

See: https://blog.codito.dev/2022/11/composer-binary-only-docker-images/
Additionally I added support for missing PHP versions through Docker Compose 🙂

Use binary-only images for installing Composer

---

src/Config/Options.php

we use `phpstan` and see this error `phpstan: Cannot cast mixed to int.`
```php
(int) $options->get('key', 100),
```
These changes will prevent the issue

improve typing

---

src/Hook/Condition/FileStaged/ThatIs.php
tests/unit/Hook/Condition/FileStaged/ThatIsTest.php

this fix allows to add a condition for *staged files contains a `php` file from either directory `foo` or `bar`* in the form
```json
"conditions": [
{
"exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\ThatIs",
"args": [
{
"ofType": "php",
"inDirectory": ["foo/", "bar/"]
}
]
}
]
```
:warning: :warning: :warning: this also contains a *minor (IMHO)* BC break: :warning: :warning: :warning: 
- before, the inDirectory filter would return true if the directory is any part of the file path or name (for example, `"inDirectory": "foo/"` was true for `foo/bar.php` (OK), `bar/foo/bar.php` (KO)
- after, the directory must be the start of the path relative to git dir
@sebastianfeldmann do not hesitate to update or reject this PR if you disagree with it

allow ThatIs filter to take multivalued options (BC BREAK)

---

configure.html
install.html

This is a follow-up of https://github.com/captainhookphp/captainhook/issues/211. Since some actions / conditions do not work when using `docker exec` without using the `-i` flag, I think the documentation should suggest using that flag. At least I do not see any disadvantage using the flag.
Reference: https://docs.docker.com/engine/reference/commandline/exec/#options

Add interactive flag to docker exec

---

src/Hook/Condition/FileStaged.php
src/Hook/Condition/FileStaged/InDirectory.php
src/Hook/Condition/FileStaged/OfType.php
src/Hook/Condition/FileStaged/ThatIs.php
tests/unit/Hook/Condition/FileStaged/AllTest.php
tests/unit/Hook/Condition/FileStaged/InDirectoryTest.php
tests/unit/Hook/Condition/FileStaged/OfTypeTest.php
tests/unit/Hook/Condition/FileStaged/ThatIsTest.php

Since you can define diff filter for placeholders it is necessary to have the same functionality for conditions to not get into a situation where the condition applies and the placeholder is empty.
Issue: #220
This pull request adds the filter functionality to all `StagedFiles` conditions for `pre-commit` hooks.

Allow diff filter setting for conditions

---

src/Config/Action.php
tests/unit/Config/ActionTest.php

In case no options exist don't create an empty option json.

Decrease action json footprint

---

src/Console/Application.php

Hi!
I've just seen the new `Uninstall` console command but it's not registered to the `Application`. 
Thanks for your amazing work!

Register uninstall console command into the Application

---

conditions.html

Fix few typos for `FileChanged` condition as well as `\CaptainHook\App\Hook\Condition\FileChanged\Any` href which was referencing `FileStaged` condition.

[GH-PAGES] Fix FileChanged condition typos

---

src/Git/ChangedFiles/Detector/PrePush.php
src/Hook/File/Action/DoesNotContainRegex.php
src/Runner/Config/Setup/Advanced.php

I have read the CONTRIBUTING.md, as this does not introduce a new feature and touches very few points in general, I did decide against opening an issue first. I hope that is ok.
`array_merge()` inside loops is quite slow. Take a look at the following PHPBench example:
```php
<?php
class ArrayMergeBench
{
/**
* @Revs(10000)
* @Iterations(5)
*/
public function benchMergeInLoop()
{
$result = [];
for ($i=0; $i<100; $i++) {
$result = array_merge($result, [$i]);
}
}
/**
* @Revs(10000)
* @Iterations(5)
*/
public function benchMergeOutsideLoop()
{
$result = [];
for ($i=0; $i<100; $i++) {
$result[] = [$i];
}
$finalResult = array_merge(...$result);
}
}
```
returns
| benchmark            | subject                   | set | revs    | its | mem_peak | mode     | rstdev | …

Refactor array_merge out of loops

---

src/Hook/Message/Action/InjectIssueKeyFromBranch.php
tests/unit/Hook/Message/Action/InjectIssueKeyFromBranchTest.php

This PR adds new option `pattern` which can be used in actions, e.g. prepare-commit-msg hook. It allows to not just prepend the subject of the commit msg with the ticket number, but also allows to add delimiters (here a colon) or other text.
**Example**:
Branch: `feature/ABC-123-my-refactoring-branch`
Commit-Message (before hook): "Some refactoring"
Commit-Message (after hook): "ABC-123: Some refactoring"
```
{
"action": "\\CaptainHook\\App\\Hook\\Message\\Action\\InjectIssueKeyFromBranch",
"options": {
"regex": "(([A-Z]+-[0-9]+))",
"pattern": "$1:",
"into": "subject",
"mode": "prepend",
"force": false
}
}
```

add new pattern option
